from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Union, Sequence
import logging
import torch
import torch.nn.functional as F
from transformers import (
    AutoConfig,
    AutoModelForSequenceClassification,
    AutoTokenizer,
    HfArgumentParser,
    Trainer,
    TrainingArguments,
    set_seed,
    PreTrainedTokenizer,
    PreTrainedModel,
    AutoModelForCausalLM
)
from torch.utils.data import Dataset
import json
import random
from sklearn.metrics import accuracy_score, f1_score
from utils import add_tokenizer

# Define and parse arguments.
@dataclass
class ModelArguments:
    model_path: Optional[str] = field(default="")
    tokenizer_path: Optional[str] = field(default="")
    num_labels: Optional[int] = field(default=2)


@dataclass
class DataArguments:
    train_data_path: str = field(default="", metadata={"help": "Path to the training data."})
    train_subset: int = field(default=10000000000,metadata={"help": "The size of the subset of the training data to use."})
    eval_data_path: str = field(default="", metadata={"help": "Path to the evaling data."})
    eval_subset: int = field(default=10000000000, metadata={"help": "The size of the subset of the eval data to use."})


@dataclass
class TrainingArguments(TrainingArguments):
    cache_dir: Optional[str] = field(default=None)
    optim: str = field(default="adamw_torch")
    merge_loss: bool = field(default=True)
    max_length: int = field(
        default=1200,
        metadata={"help": "Maximum sequence length. Sequences will be right padded (and possibly truncated)."},
    )
    test_only:bool = field(default=False)
    checkpoint_dir:str = field(default="")
    deepspeed: str = field(default="")


def preprocess_function(sources, next_steps, tokenizer: PreTrainedTokenizer):
    tokenized_list = []
    for state, next_step in zip(sources, next_steps):
        tokenized_next_step = tokenizer(next_step, padding=False, max_length=tokenizer.model_max_length,truncation=True, return_tensors="pt").input_ids[0]
        tokenized_state = tokenizer(state, padding=False, max_length=max(tokenizer.model_max_length - len(tokenized_next_step),1), truncation=True, return_tensors="pt").input_ids[0]
        tokenized_list.append(torch.cat((tokenized_state, tokenized_next_step), dim=0))
    return dict(input_ids=tokenized_list)


class RewardDataset(Dataset):
    def __init__(self, data_path, tokenizer: PreTrainedTokenizer,num_lables):
        random.seed(42)
        cor_step,err_step=0,0
        super(RewardDataset, self).__init__()
        logging.warning("Loading data...")
        with open(data_path, 'r', encoding='utf-8') as f:
            list_data_dict = json.load(f)
        random.shuffle(list_data_dict)
        logging.warning("Formatting inputs...")
        prompt = "### Instruct:\nThe steps in 'Selected steps' are the correct problem-solving steps of the problem, while the steps in 'Next step:' are the next problem-solving steps generated by an AI agent based on the steps in 'Selected steps:'.You need to rate the step in 'Next step:' based on it`s usefulness and correctness.\n\n"
        sources, self.labels, next_steps = [], [], []
        for idx, example in enumerate(list_data_dict):
            for index in range(example["total_steps"]):
                try:
                    state = example[f"state{index}"]
                except KeyError:
                    continue
                if example[f"step{index}"] is None:
                    print(list_data_dict[idx]["question"],example[f"state{index}"])
                for item in example[f"step{index}"]:
                    sources.append(prompt+state)
                    next_steps.append('Next step:' + item["text"])
                    if item["rating"]==1 or item["rating"]==0:
                        rating = [1,0]
                        cor_step+=1
                    else:
                        rating = [0,1]
                        err_step+=1
                    if num_lables==2:
                        label=rating
                    self.labels.append(label)
        self.sources = [{"source":sources[i],"next_step":next_steps[i]} for i in range(len(sources))]
        print(f"{cor_step} correct steps,{err_step} error steps")

    def __len__(self):
        return len(self.sources)

    def __getitem__(self, i):
        return dict(input_ids=self.sources[i], labels=self.labels[i])

    def select(self, start,end):
        self.sources = self.sources[start:end]
        self.labels = self.labels[start:end]


@dataclass
class RewardDataCollatorWithPadding(object):
    tokenizer: PreTrainedTokenizer
    def __call__(self, instances: Sequence[Dict]) -> Dict[str, str]:
        labels = [instance["labels"] for instance in instances]
        sources=[instance["input_ids"]["source"] for instance in instances]
        next_steps=[instance["input_ids"]["next_step"] for instance in instances]
        data_dict = preprocess_function(sources, next_steps, self.tokenizer)
        input_ids = torch.nn.utils.rnn.pad_sequence(data_dict["input_ids"], batch_first=True,padding_value=self.tokenizer.pad_token_id)
        labels = torch.tensor(labels).float()
        return dict(
            input_ids=input_ids,
            labels=labels,
            attention_mask=input_ids.ne(self.tokenizer.pad_token_id),
        )
    

def compute_metrics(eval_pred):
    preds = eval_pred.predictions.argmax(-1)
    label_format = eval_pred.label_ids.argmax(-1)
    f1 = f1_score(label_format, preds, average="weighted")
    acc = accuracy_score(label_format, preds)
    return {"accuracy": acc, "f1": f1}
 

def main():
    parser = HfArgumentParser((ModelArguments, DataArguments, TrainingArguments))
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
    set_seed(training_args.seed)
    tokenizer = AutoTokenizer.from_pretrained(model_args.tokenizer_path)
    model = AutoModelForSequenceClassification.from_pretrained(model_args.model_path, attn_implementation="flash_attention_2", num_labels=model_args.num_labels, torch_dtype=torch.bfloat16) if model_args.num_labels else AutoModelForCausalLM.from_pretrained(model_args.model_path, torch_dtype=torch.bfloat16)
    tokenizer.model_max_length = training_args.max_length
    add_tokenizer(model, tokenizer)
    print(model.config._attn_implementation)
    train_dataset = RewardDataset(data_args.train_data_path, tokenizer, model_args.num_labels)
    if data_args.eval_data_path=="": 
        eval_dataset = RewardDataset(data_args.train_data_path, tokenizer, model_args.num_labels)
        train_dataset.select(0,int(len(train_dataset)*0.95))
        eval_dataset.select(int(len(eval_dataset)*0.95),len(eval_dataset))
    else:
        eval_dataset = RewardDataset(data_args.eval_data_path, tokenizer, model_args.num_labels)
    print(len(train_dataset),len(eval_dataset))
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        compute_metrics=compute_metrics,
        data_collator=RewardDataCollatorWithPadding(tokenizer=tokenizer),
    )
    if training_args.test_only:
        preds = trainer.predict(test_dataset=eval_dataset)
        predictions = torch.tensor(preds.predictions)
        predictions=F.softmax(predictions, dim=-1)
        in_labels = preds.label_ids
        sampled_numbers = random.sample(range(len(eval_dataset)), 30)
        for i in sampled_numbers:
            print('预测值：', float(predictions[i][1]), '标签：', in_labels[i][0], "\n")
        print(preds.metrics)
    else:
        checkpoint_dir=training_args.checkpoint_dir if training_args.checkpoint_dir!="" else False
        trainer.train(resume_from_checkpoint=checkpoint_dir)
        print(trainer.evaluate(eval_dataset=eval_dataset))


if __name__ == "__main__":
    main()
